### ISSUE TITLE
Where can I find the streamdiffusion.tools.install-tensorrt module?

### ISSUE THREAD

**Issue by liuchangzong** [cumulo-autumn/StreamDiffusion#105]
I can't find the  streamdiffusion.tools.install-tensorrt module in command: python -m  streamdiffusion.tools.install-tensorrt module.
Where Can I find it?
thanks a lot!

**Comment by rqtqp** [comment]
check here:
https://github.com/cumulo-autumn/StreamDiffusion/blob/main/src/streamdiffusion/tools/install-tensorrt.py
