### ISSUE TITLE
TensorRT : Supplied binding dimension problem

### ISSUE THREAD

**Issue by ccarmatic** [cumulo-autumn/StreamDiffusion#158]
CUDA 11.8, Python 3.10.14, Windows 11
Installed as per instructions:
`pip3 install torch==2.1.0 torchvision==0.16.0 xformers --index-url https://download.pytorch.org/whl/cu118`
`pip install git+https://github.com/cumulo-autumn/StreamDiffusion.git@main#egg=streamdiffusion[tensorrt]`
`python -m streamdiffusion.tools.install-tensorrt`

I managed to bypass https://github.com/cumulo-autumn/StreamDiffusion/issues/157#issue-2365826045 and make Streamdiffusion run by **uninstalling nvidia-cudnn-cu11 after running the Streamdiffusion TensorRT installation script**

This allows Streamdiffusion to finish building the engines, but when is doing the img2img process with image resolution of 512x512, it gives these error messages for every frame it generates:

```
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2] for bindings[1] exceed min ~ max range at index 0, maximum dimension in profile is 1, minimum dimension in profile is 1, but supplied dimension is 2.
    )
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2,77,768] for bindings[2] exceed min ~ max range at index 0, maximum dimension in profile is 1, minimum dimension in profile is 1, but supplied dimension is 2.
    )
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2,4,64,64] for bindings[0] exceed min ~ max range at index 0, maximum dimension in profile is 1, minimum dimension in profile is 1, but supplied dimension is 2.
    )
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2] for bindings[1] exceed min ~ max range at index 0, maximum dimension in profile is 1, minimum dimension in profile is 1, but supplied dimension is 2.
    )
```

and the image looks very corrupted, like it is made of rectangular tiles, and text prompts have no effect:
![image](https://github.com/cumulo-autumn/StreamDiffusion/assets/67438380/a4396534-8e22-4fd8-9a22-4110d65041de)
for reference this is the input image: 
![image](https://github.com/cumulo-autumn/StreamDiffusion/assets/67438380/bc388efb-c34a-4057-8786-0d1bf4563c40)

**Comment by ccarmatic** [comment]
I have fixed the problem, here is how:

1. Install CUDA 12.1 
2. Install PyTorch for CUDA 12.1 `pip3 install torch==2.1.0 torchvision==0.16.0 xformers --index-url https://download.pytorch.org/whl/cu121`
3. **This step is important:** Install the CUDA 12 version of TensorRT : `python -m pip install --pre --extra-index-url https://pypi.nvidia.com/ tensorrt==9.0.1.post12.dev4 --no-cache-dir ` notice that the version is 9.01.post**12**.dev4 , unlike the version installed by the StreamDiffusion install script which is 9.01.post11.dev4
4. Install the version of nvidia-cudnn-cu12 which StreamDiffusion uses:  `python -m pip install nvidia-cudnn-cu12==8.9.4.25 --no-cache-dir`
5. **This step is important:** Copy the contents of "Python310\Lib\site-packages\nvidia\cudnn\bin\" to "Python310\Lib\site-packages\torch\lib\" ; You will be replacing the cudnn dll files which came with Torch , with the version you manually installed in the previous step
6. Run a Python script which engages the TensorRT extension, such as in my previous post https://github.com/cumulo-autumn/StreamDiffusion/issues/157#issue-2365826045 , and let it build the engines under the conditions you have made in the previous steps

StreamDiffusion should now work under CUDA 12.1 with correct functioning of the TensorRT extension

**Comment by potesd** [comment]
You're a lifesaver!! stupid freaking defunct post11 link :(

**Comment by ccarmatic** [comment]
Does anyone know how to update the install script? So that it has these corrections , as well as fixing this https://github.com/cumulo-autumn/StreamDiffusion/issues/185
