### ISSUE TITLE
problem installing onnx 1.16.3?

### ISSUE THREAD

**Issue by mmattyg** [cumulo-autumn/StreamDiffusion#159]
With python 3.10, cuda 11.8, the install stops midway and give this error:

INFO: pip is looking at multiple versions of streamdiffusion[tensorrt] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.16.3; extra == "tensorrt" (from streamdiffusion[tensorrt]) (from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0)
ERROR: No matching distribution found for onnxruntime==1.16.3; extra == "tensorrt"

Any idea how I could fix this?

**Comment by mmattyg** [comment]
solution: make sure you're with Python 3.10

**Comment by ccarmatic** [comment]
Hello, can you elaborate on your solution? There is an open issue about this https://github.com/cumulo-autumn/StreamDiffusion/issues/185
