### ISSUE TITLE
 TensorRT instalation couse error on Linux

### ISSUE THREAD

**Issue by animede** [cumulo-autumn/StreamDiffusion#16]
On Linux environment, TensorRT instalation couse error.
libcublasLt.so.11 is not installed. Cpying this file from other rep, TensorRT instalation is succeded.
What is correct instalation on Linux?
Environment - Linux20.04-jp + RTX4090

**Comment by GothParrot** [comment]
@animede how did you resolve this?

**Comment by animede** [comment]
I had copied libcublasLt.so.11 from other rep to tenserrt directory, my TensorRT is working fine. Thanks.
