### ISSUE TITLE
新しい加速モデル?それとも古いリアルタイム描画ノードでしょうか?

### ISSUE THREAD

**Issue by aimarxjg** [cumulo-autumn/StreamDiffusion#47]
効果は非常によく似ています （https://github.com/shadowcz007/comfyui-mixlab-nodes）
これは新しい加速モデルを最初から作成したのでしょうか? それともリアルタイム ペイント機能を分離して単独で使用しただけですか? 選択領域をドラッグして調整することはできませんか? 生成されるステップ数を調整することはできませんか?サンプラースケジューラーなどを変更しますか？まったく機能がないのですか？

**Comment by YacratesWyh** [comment]
新しテック、mixlabはただツール統合

**Comment by Pythonpa** [comment]
Is it possible to retrofit this for use on comfyui or as a node?
