### ISSUE TITLE
will support webUI?

### ISSUE THREAD

**Issue by qidai77777** [cumulo-autumn/StreamDiffusion#69]

**Comment by teftef6220** [comment]
Thanks for your comments.

We have to find out how compatible our project is with Gradio. 
This may take some time, but I will share it with the developer team.

**Comment by bropines** [comment]
> Thanks for your comments.
> 
> We have to find out how compatible our project is with Gradio. This may take some time, but I will share it with the developer team.



> Thanks for your comments.
> 
> We have to find out how compatible our project is with Gradio. This may take some time, but I will share it with the developer team.

in general, it would not be bad to write a plugin for Sd automatic and comfyUI?

**Comment by continue-revolution** [comment]
This is a PURELY system paper instead of ML paper, which means that it would be non-trivial to support it in any variation of WebUI. Also I believe that we almost certainly need to build a new WebUI (certainly with A1111 backend) and get rid of Gradio, to really have a good real time experience.
